import { InventoryItem } from '../types';

export const SEED_INVENTORY: InventoryItem[] = [
  // Chemicals – Table 1
  { id: 'C001', name: '195B', type: 'Chemical', qty: 443, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C002', name: 'ANT B', type: 'Chemical', qty: 60, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C003', name: 'FOS 151', type: 'Chemical', qty: 75.5, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C004', name: 'Shampun abi', type: 'Chemical', qty: 240, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C005', name: 'AR2', type: 'Chemical', qty: 406, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C006', name: 'AKH', type: 'Chemical', qty: 262, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C007', name: 'LS 12', type: 'Chemical', qty: 414, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C008', name: 'TSK', type: 'Chemical', qty: 299, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C009', name: 'CRFX', type: 'Chemical', qty: 100, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C010', name: 'Mimuza', type: 'Chemical', qty: 242, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C011', name: 'RDE', type: 'Chemical', qty: 282, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C012', name: 'NTR', type: 'Chemical', qty: 80.9, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C013', name: 'KEN 2000', type: 'Chemical', qty: 100, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C014', name: 'LW4', type: 'Chemical', qty: 124, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C015', name: 'DSI', type: 'Chemical', qty: 6.5, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C016', name: 'DSW', type: 'Chemical', qty: 79.5, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C017', name: 'DLX', type: 'Chemical', qty: 300, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C018', name: 'PHN', type: 'Chemical', qty: 100, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C019', name: '1000K', type: 'Chemical', qty: 100, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C020', name: 'FDC', type: 'Chemical', qty: 78, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C021', name: 'Chrome', type: 'Chemical', qty: 56, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C022', name: 'LTE', type: 'Chemical', qty: 75, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C023', name: 'DSB', type: 'Chemical', qty: 50, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C024', name: 'DSG', type: 'Chemical', qty: 569, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C025', name: 'DGS', type: 'Chemical', qty: 700, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C026', name: 'ACID Green', type: 'Chemical', qty: 24, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C027', name: 'Acid Maroon', type: 'Chemical', qty: 12, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C028', name: 'Acid Blue Mtr', type: 'Chemical', qty: 14, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C029', name: 'black X5', type: 'Chemical', qty: 102.2, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C030', name: 'Brown VS', type: 'Chemical', qty: 225, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C031', name: 'Blue RR', type: 'Chemical', qty: 114, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C032', name: 'Yellow 50AD', type: 'Chemical', qty: 236, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C033', name: 'Farmic acid', type: 'Chemical', qty: 281, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C034', name: 'Amonia', type: 'Chemical', qty: 452, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C035', name: 'Yag giderici', type: 'Chemical', qty: 180, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C036', name: 'Soda Format', type: 'Chemical', qty: 52, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C037', name: 'Migrozin', type: 'Chemical', qty: 15, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C038', name: 'LESTINE KOMBINE', type: 'Chemical', qty: 60, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C039', name: 'BIOCIDE CMI BAKTERIA', type: 'Chemical', qty: 20, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C040', name: 'HX', type: 'Chemical', qty: 57, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C041', name: 'RAM', type: 'Chemical', qty: 118, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C042', name: 'AG 25', type: 'Chemical', qty: -1, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C043', name: 'BrownSJ', type: 'Chemical', qty: 21, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C044', name: 'black F2RA', type: 'Chemical', qty: 0, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C045', name: 'Brown ORG', type: 'Chemical', qty: 18, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C046', name: 'Orange RGN', type: 'Chemical', qty: 4.5, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C047', name: 'Soda bicarbonate', type: 'Chemical', qty: 43, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C048', name: 'P3P', type: 'Chemical', qty: 15, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C049', name: 'Brown P3P', type: 'Chemical', qty: 16.5, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C050', name: 'Oxalic ACID', type: 'Chemical', qty: 3, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C051', name: 'Teknik Soda', type: 'Chemical', qty: 17, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C052', name: "Eski Balig' Yog'", type: 'Chemical', qty: 30, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C053', name: 'WME', type: 'Chemical', qty: 260, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C054', name: 'TF30', type: 'Chemical', qty: 60, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C055', name: 'SLK', type: 'Chemical', qty: -5, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C056', name: 'black dye', type: 'Chemical', qty: 11.5, unit: 'kg', price: 0, currency: 'USD' },
  // Chemicals – Table 2
  { id: 'C057', name: 'Red kp', type: 'Chemical', qty: 156, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C058', name: 'Black kp', type: 'Chemical', qty: 150, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C059', name: 'Lemon kp', type: 'Chemical', qty: 120, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C060', name: 'Blue kp', type: 'Chemical', qty: 79, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C061', name: 'Caramel Kp', type: 'Chemical', qty: 61, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C062', name: 'CPF 4119', type: 'Chemical', qty: 120, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C063', name: 'CMT 205', type: 'Chemical', qty: 105.3, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C064', name: 'PAC SB', type: 'Chemical', qty: 127, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C065', name: 'CPF 4164', type: 'Chemical', qty: 30, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C066', name: 'CPF 4127', type: 'Chemical', qty: 116.1, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C067', name: 'WAX VWX 3500', type: 'Chemical', qty: 297.5, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C068', name: 'PBC 5A', type: 'Chemical', qty: 370.3, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C069', name: 'CRE 1501', type: 'Chemical', qty: 105.5, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C070', name: 'LH 016/40', type: 'Chemical', qty: 802, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C071', name: 'LH 061/30', type: 'Chemical', qty: -7, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C072', name: 'Compak Binder abi', type: 'Chemical', qty: 103, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C073', name: 'WAX abi', type: 'Chemical', qty: 96.5, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C074', name: 'Micro abi', type: 'Chemical', qty: 63, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C075', name: 'OQ pigment', type: 'Chemical', qty: 106, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C076', name: 'Black pigment', type: 'Chemical', qty: 27, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C077', name: 'CPF 4154', type: 'Chemical', qty: 16, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C078', name: 'Etil grikom', type: 'Chemical', qty: 82, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C079', name: 'Poliretan', type: 'Chemical', qty: 12.6, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C080', name: 'nanolux yellow', type: 'Chemical', qty: 38, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C081', name: 'glazia 60 binder', type: 'Chemical', qty: 110, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C082', name: 'glazia 75 binder', type: 'Chemical', qty: 108, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C083', name: 'Micro binder Nestle', type: 'Chemical', qty: 28, unit: 'kg', price: 0, currency: 'USD' },
  { id: 'C084', name: 'Laq nestle', type: 'Chemical', qty: 21, unit: 'kg', price: 0, currency: 'USD' },
  // Other
  {
    id: 'W001',
    name: 'Wet Blue Hide',
    type: 'Wet Blue',
    qty: 3000,
    unit: 'piece',
    price: 12.0,
    currency: 'USD',
  },
];

export const DEFAULT_SETTINGS = {
  language: 'en' as const,
  lowStockThreshold: 50,
  exchangeRates: {
    USD: 1,
    EUR: 1.08,
    UZS: 0.000078,
  },
};
